length_vec_a = np.linalg.norm(vec_a_b)
# length_vec_c = np.linalg.norm(vec_b_c)
# inner_product = np.inner(vec_a_b, vec_b_c)
# cos = inner_product / (length_vec_a * length_vec_c)
# rad = np.arccos(cos)
# print(np.rad2deg(rad))